### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by pangloss** [jordanlewis/data.union-find#5]
Hi Jordan, 

I just discovered this library today and it looks very useful! I see that nearly a year ago some work on a transient version of union-find was merged, but you haven't made any release. I'm wondering if that is because there is a problem with the transient version, or if perhaps something else has held it up. If a release is possible, it would be great if you could do that!

Thanks,
Darrick

**Comment by jordanlewis** [comment]
Hey Darrick,

I don't think there's a problem - I've just been busy with other stuff. I can definitely make a release happen. Thanks for your interest!

- Jordan
